import { describe, expect, test } from "bun:test";
import { compile, parse, run, tokenize } from "../src/index.ts";

describe("lexer", () => {
  test("tokenizes assignment with temperature unit", () => {
    const tokens = tokenize("🌡 ← 45°C");
    const number = tokens.find((t) => t.type === "Number");

    expect(number).toBeDefined();
    expect(number?.unit).toBe("°C");
    expect(number?.number).toBe(45);
  });
});

describe("parser", () => {
  test("parses function definition", () => {
    const ast = parse("ƒ double(x) → x × 2");

    expect(ast.type).toBe("Program");
    expect(ast.statements[0].type).toBe("FunctionDef");
  });

  test("parses backend route", () => {
    const ast = parse('GET "/ping" → "pong"');

    expect(ast.statements[0].type).toBe("Route");
  });

  test("parses object literal", () => {
    const ast = parse("x ← 🧬 { a ← 1 }");

    expect(ast.statements[0].type).toBe("Assignment");
  });
});

describe("runtime", () => {
  test("runs hello world", async () => {
    const result = await run('🧪 → "Hello, Chemistry!"');

    expect(result.outputs.join("\n")).toContain("Hello, Chemistry!");
  });

  test("runs Q10 stability calculation", async () => {
    const source = `
🌡₁ ← 25°C
🌡₂ ← 45°C
⏱ ← 15d
Q₁₀ ← 2

EQ ⟶ ⏱ × Q₁₀^((🌡₂−🌡₁)/10)

→ EQ
`;

    const result = await run(source);
    const output = result.outputs.join("\n");

    expect(output).toContain("60d");
  });

  test("supports function calls", async () => {
    const source = `
ƒ double(x) → x × 2
→ double(21)
`;

    const result = await run(source);
    expect(result.outputs.join("\n")).toContain("42");
  });

  test("runs object output", async () => {
    const result = await run("→ 🧬 { a ← 1 }");

    expect(result.outputs.join("\n")).toContain('"a":1');
  });

  test("throws styled error for unknown symbol", async () => {
    await expect(run("→ 🧬")).rejects.toThrow();
  });
});

describe("compiler", () => {
  test("compiles KevLang to JavaScript runner", () => {
    const js = compile("🌡 ← 45°C\n→ 🌡");

    expect(js).toContain("kevlang");
    expect(js).toContain("Generated by KevLang");
  });
});
