import { parse } from "./parser.js";
import { VERSION } from "./symbols.js";

export function compile(source: string): string {
  parse(source);

  const serializedSource = JSON.stringify(source);

  return `#!/usr/bin/env bun
// Generated by KevLang v${VERSION}
// Code like a chemist. Build like an engineer.

const source = ${serializedSource};

async function __kevLoad() {
  const candidates = [
    "kevlang",
    "./index.js",
    "./dist/index.js",
    "../dist/index.js",
    "../../dist/index.js"
  ];

  let lastError;

  for (const candidate of candidates) {
    try {
      return await import(candidate);
    } catch (err) {
      lastError = err;
    }
  }

  throw new Error(
    "Unable to import kevlang runtime. Install it with: npm install kevlang\\n" +
      (lastError ? String(lastError) : "")
  );
}

const kev = await __kevLoad();

try {
  await kev.run(source, {
    animation: false,
    print: console.log
  });
} catch (err) {
  if (kev.formatKevError) {
    console.error(kev.formatKevError(err, source));
  } else {
    console.error(err);
  }

  process.exitCode = 1;
}
`;
}
